### ISSUE TITLE
Wrong path to directory (duplicates the C:/ destination)

### ISSUE THREAD

**Issue by Pipazoul** [etiennepinchon/magixjs#8]
When I make a change on files I get this error, is there a way to correct it ?

`{ Error: ENOENT: no such file or directory, open 'C:\C:\Users\yassi\test\documents\App.coffee'
}`

**Comment by karanganesan** [comment]
For PC user: After changing the App.coffee file run "magix build" and then "magix launch" .... then this error will not come ...
